#!/home/peter/playground/reviewboard/rb_venv/bin/python3

import tkinter as tk

main = tk.Tk()

# ------------------ GENERAL SETUP --------------------------

main.geometry("500x200")

# transparency
main.wait_visibility(main)
main.wm_attributes('-alpha',0.9)

# -----------------------------------------------------------

label_comment=tk.Label(main, text="Comment: ")
#label_comment.pack()
label_comment.grid(row=0, column=0)

entry_comment=tk.Entry(main, bd = 5)
#entry_comment.pack()
entry_comment.grid(row=0, column=1)

button = tk.Button(main, text="Ok")
button.grid(row=1, column=0)
#button.pack()

main.mainloop()